name: Update NYT Puzzle Stats

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust time as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update NYT Stats
        env:
          NYT_COOKIE: ${{ secrets.NYT_COOKIE }}
        run: |
          python nyt_stats.py
          
      - name: Checkout profile repository
        uses: actions/checkout@v3
        with:
          repository: mpartificer/mpartificer
          path: profile-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Copy README to profile repository
        run: |
          # Check if the target README exists
          if [ -f profile-repo/README.md ]; then
            echo "Profile README exists, updating it"
            
            # Extract content between markers from the source README
            START_MARKER="<!-- NYT_STATS_START -->"
            END_MARKER="<!-- NYT_STATS_END -->"
            
            # Extract the stats content from our updated README
            STATS_CONTENT=$(sed -n "/${START_MARKER}/,/${END_MARKER}/p" README.md)
            
            # Check if profile README already has markers
            if grep -q "${START_MARKER}" profile-repo/README.md; then
              echo "Markers found in profile README, updating content"
              # Replace content between markers in profile README
              sed -i "/${START_MARKER}/,/${END_MARKER}/c\\${STATS_CONTENT}" profile-repo/README.md
            else
              echo "Adding markers and content to profile README"
              # Append markers and content to profile README
              echo -e "\n${STATS_CONTENT}" >> profile-repo/README.md
            fi
          else
            echo "Profile README does not exist, creating it"
            # Create a new README with stats content
            cp README.md profile-repo/README.md
          fi
          
      - name: Commit and push profile changes
        run: |
          cd profile-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update NYT puzzle stats" && git push)
